spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genieary
    username: root
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
jwt:
  #geniearyecretaccesstokengeniearyecretaccesstokengeniearyecretaccesstoken
  secret: Z2VuaWVhcnllY3JldGFjY2Vzc3Rva2VuZ2VuaWVhcnllY3JldGFjY2Vzc3Rva2VuZ2VuaWVhcnllY3JldGFjY2Vzc3Rva2Vu
  expiration: 86400000 # 1 day in ms
