spring:
  datasource:
    url: jdbc:mysql://localhost:3306/genieary
    username: root
    password: ${DB_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

jwt:
  #geniearyecretaccesstokengeniearyecretaccesstokengeniearyecretaccesstoken
  secret: ${access_token_secret}
  expiration: ${expiration}
  refresh-expiration: ${refresh_expiration}
kakao:
  client-id: ${REST_API_KEY}
  client-secret: ${KAKAO_SECRET}
  redirect-uri: ${REDIRECT_URI}
